baseURL = "http://clanonda.github.io/"
languageCode = "en-us"
defaultContentLanguage = "it"
title = "Challenge 2020 - Sfida Relazionale"
theme = "ananke"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "logoonda.jpg"
  description = "Sfida del clan onda 2020"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-gray"
  featured_image = "onda.jpg"
  recent_posts_number = 2
